import "@/styles/globals.css";

import { type Metadata } from "next";
import { Lemon, IBM_Plex_Sans_KR } from 'next/font/google'
import {  } from 'next/font/google'
 
const lemon = Lemon({
  weight: '400',
  subsets: ['latin'],
})
const ibm = IBM_Plex_Sans_KR({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "AI chatbot",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={lemon.className}>
      <body>{children}</body>
    </html>
  );
}
